version: '3.7'
services:
  app:
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - 8050:8050
    volumes:
      - ./app:/app
      - ./data:/data
    environment:
      - POSTGRES_USER=postgis
      - POSTGRES_PASSWORD=postgis
      - POSTGRES_DB=mydatabase
